#CI项目名
name: REDMI-AX6000

on:
  #自动编译：每天早上4点
  schedule:
    - cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  owrt_config:
    #调用公用编译核心OWRT-CORE.yml
    uses: ./.github/workflows/redmi.yml
    with:
      #编译，REDMIAX6000M通用配置
      OWRT_TARGET: redmiax6000
      #默认主题
      OWRT_THEME: argon
      #默认主机名
      OWRT_NAME: REDMI-AX6000
      #默认密码，仅作展示，更改无效
      OWRT_PW: password
      #默认地址
      OWRT_IP: 192.168.30.1
      #默认源码
      OWRT_URL: https://github.com/NekokeCore/immortalwrt-mt798x-24.10.git
